<?php

namespace AppBundle\Repository;

/**
 * ElectricalReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectricalReviewRepository extends \Doctrine\ORM\EntityRepository
{
}
