<?php

namespace AppBundle\Repository;

/**
 * TavernRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TavernRepository extends \Doctrine\ORM\EntityRepository
{
}
